#!/usr/bin/env bash
# Note-finding script for the LRK knowledge base
set -euo pipefail

if [ $# -lt 1 ]; then
    printf "Usage: %s <metadata>...\n" "$0" > /dev/stderr
    exit 1
fi

lrk-list |
while read file; do
    if [ -z "$(lrk-get "$1" $file)" ]; then
        continue
    fi
    printf "%s" "$file"
    for md in "$@"; do
        val=$(lrk-get $md $file)
        if [ ! -z "$val" ]; then
            printf "\t%s" "$val"
        fi
    done
    printf "\n"
done |
fzf -m |
while read line; do
    printf "$line" | perl -ne 'm/^([^\t]*)\t/ && print "$1\n"'
done
