#!/usr/bin/env perl
# Metadata-fetching script for the LRK knowledge base.
use strict;
use warnings;

my $lrk_path =	((exists $ENV{'LRK_DIR'})
		? $ENV{'LRK_DIR'}
		: $ENV{'HOME'} . '/.lrk');

sub metadata_get {
	my ($md, $fn) = @_;

	my $path = "$lrk_path/$fn";

	open my $fd, '<', $path or die "Failed to open $path: $!";

	for (<$fd>) {
		if (/^$md: (.*)$/) {
			print "$1\n";
			last;
		}
	}
	close $fd;
}

if ($#ARGV != 1) {
	die "Usage: $0 <metadata> <file>\n";
}

metadata_get($ARGV[0], $ARGV[1]);
