#!/usr/bin/env bash
# Note-creating script for the LRK knowledge base
set -euo pipefail

path="$HOME/.lrk"

if [ ! -z "${LRK_DIR+x}" ]; then
    path="$LRK_DIR"
fi

fname="$(date +'%Y%m%d%H%M%S')"

cat >$path/$fname<<EOF
TITLE:
DATE: $(date +"%Y-%m-%d %H:%M:%S")
TAGS:
---
EOF

printf "$path/$fname\n"
