#!/usr/bin/env bash
# Note-creating script for the LRK knowledge base
set -euo pipefail

path="$HOME/.lrk"

if [ ! -z "${LRK_DIR+x}" ]; then
    path="$LRK_DIR"
fi

find "$path" -type f -printf "%f\n"
